### ISSUE TITLE
Tasks with failed dependencies show as running in Task Manager

### ISSUE THREAD

**Issue by dykeag** [cnshenj/vscode-task-manager#1]
If I have a task with a dependency that fails, the Task Manager seems to think that the parent task never exits. It shows the spinning circle and the Stop button, but pressing either of those buttons has no effect.

**Comment by cnshenj** [comment]
When that happened, were you able to stop the parent task using VSCode "Terminate task" command?

**Comment by dykeag** [comment]
The parent task was no longer running - it had exited already. But Task Manager did not seem to realize this.

**Comment by dykeag** [comment]
I've actually narrowed it down further. If you have a task which has no "command" - it ONLY has dependencies (this is a valid configuration according to VSCode) - then Task Manager thinks the task never exits

**Comment by cnshenj** [comment]
Unfortunately this is a vscode [bug](https://github.com/microsoft/vscode/issues/81777). It exposes an array `vscode.tasks.taskExecutions` for extensions to check which task is running. It is not cleaned up properly if a "no command" parent task is executed and completed.

**Comment by cnshenj** [comment]
VSCode fixed its bug in Oct 2019. Task dependencies should work properly for VSCode version 1.40 or later.
