### ISSUE TITLE
Can we hide tasks?

### ISSUE THREAD

**Issue by ddnexus** [cnshenj/vscode-task-manager#14]
There may be some task that is only used as a `preLaunchTask` that is sort of internal and not useful to have in the list for manual launch. Is there any way to hide them?

**Comment by cnshenj** [comment]
VSCode doesn't have a built-in property to tell whether a task is **only** used as `preLaunchTask`.

Please update Task Manager to version 0.6.0. Then use configuration `taskManager.exclude` to set a regular expression to match tasks you want to exclude.

For example, make sure all your `preLaunchTask`s are prefixed by `pre-`, then set `taskManager.exclude` to `^pre-`.

**Comment by ddnexus** [comment]
This is perfect! Thank you!
