### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by clecap** [cnshenj/vscode-task-manager#18]
There are numerous conditions on which the error handling fails and the task manager still presents a spinning icon as if the task were still executing.

One example is a shell command where the path in the command property of the tasks.json file has a typo.

What makes this but even worse: You cannot just stop the the task in the task manager but it continues spinning until a restart of the workspace; not even a refresh tasks in the task manager helps.

**Comment by cnshenj** [comment]
When that happens, can you stop the task via the native VSCode command "Tasks: Terminate Task" (you can find it in the Command Palette <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)?

**Comment by clecap** [comment]
I did two tests. One with a command which is not in the path and one with the task sleep infinity. None of the two I can abort that way.

**Comment by cnshenj** [comment]
Task Manager is essentially a UI of the VSCode tasks. It relies on the native VSCode task API to perform operations. The fact that you can't even use native VSCode task commands to terminate those shell commands means it is a VSCode issue. Please open an issue in VSCode repository instead.

**Comment by clecap** [comment]
Sorry to disappoint you, but I rechecked this. It is not that VSCode fails to terminate the commands - it is that task manager fails to recognize this correctly. I did the tests again: The tasks are gone. Task manager continues to display them as running.

Request to reopen issue #18.
