### ISSUE TITLE
Sort tasks by project in addition to type/provider

### ISSUE THREAD

**Issue by stefanobartoletti** [cnshenj/vscode-task-manager#2]
VIsual Studio Code gives the ability to add multiple directories/projects to the current workspace.

Right now your extension lists task sorted only by their type/provider (i.e. `npm` tasks, `gulp` tasks), it works nicely when working on a single project, but when using worskaces where one has added multiple ones, all the tasks are listed together, making it impossible to tell them apart.

In example, I can have a workspace where I have added a directory called `project-a` and another called `project-b`, each one of them with its own `package.json`, `gulpfile.js`, and so on.

Right now, your extension list all tasks together, like this:
```
npm
| - install
| - install
| - postinstall
| - postinstall
| - watch
| - watch
```
I think that it would be better to have something like this:
```
project-a
| - npm
| | - install
| | - postinstall
| | - watch
project-b
| - npm
| | - install
| | - postinstall
| | - watch
```
As an example, there is another extension that already do this, if you want to have a look: https://marketplace.visualstudio.com/items?itemName=spmeesseman.vscode-taskexplorer

**Comment by cnshenj** [comment]
I have published version 0.3.0 to support multi-root workspaces.
